apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: health-ingester-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/health
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: health-ingester-credentials-vault
    transformation:
      excludeRaw: true
      templates:
        DATABASE_USER:
          text: '{{ get .Secrets "HEALTH_INGESTER_DB_USER" }}'
        DATABASE_PASSWORD:
          text: '{{ get .Secrets "HEALTH_INGESTER_DB_PASSWORD" }}'
        WEBHOOK_TOKEN:
          text: '{{ get .Secrets "HEALTH_WEBHOOK_TOKEN" }}'

  rolloutRestartTargets:
    - kind: Deployment
      name: health-ingester
