apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-minio-dev-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/cnpg-minio-dev-credentials
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: cnpg-minio-dev-credentials-vault
    transformation:
      excludeRaw: true

  rolloutRestartTargets:
    - kind: StatefulSet
      name: minio
