apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/pgadmin
  - ../../../base/wallabag
  - ../../../base/health-ingester
  - ../../../base/n8n
  - ../../../base/authentik
  - ../../../base/nodered
  - ../../../base/docmost

patches:
  - path: patches/wallabag/wallabag-env.yaml
  - path: patches/wallabag/wallabag-vault-secret.yaml
  - path: patches/pgadmin/pgadmin-vault-secret.yaml
  - path: patches/n8n/n8n-env.yaml
  - path: patches/n8n/n8n-vault-secret.yaml
  - path: patches/authentik/authentik-env.yaml
  - path: patches/nodered/nodered-env.yaml
  - path: patches/docmost/docmost-env.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: wallabag
    patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - worker-1
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pgadmin
    patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - worker-1

configMapGenerator:
  - name: health-ingester-config
    literals:
      - LISTEN_ADDRESS=:8080
      - DATABASE_HOST=central-postgres-dev-rw.dev.svc.cluster.local
      - DATABASE_PORT=5432
      - DATABASE_NAME=health_dev
      - DATABASE_SSLMODE=disable
      - GRAFANA_DATABASE_ROLE=health_grafana_dev_user

images:
  - name: wallabag/wallabag
    newName: wallabag/wallabag
    digest: sha256:4a527e027e0d59e87c14225ef11e005af3d4890374202ad319ce5e63dfc66709
