apiVersion: v1
kind: Secret
metadata:
  name: github-homelab-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/hshamsadd/homelab.git
  username: hshamsadd
  password: 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
