apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: DATABASE_HOST_PLACEHOLDER
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: DATABASE_NAME_PLACEHOLDER
            - name: N8N_HOST
              value: DOMAIN_PLACEHOLDER
            - name: WEBHOOK_URL
              value: "http://DOMAIN_PLACEHOLDER/"
