#cloud-config

hostname: ${vm_hostname}
manage_etc_hosts: true
ssh_pwauth: false
disable_root: true

users:
  - name: ${vm_user}
    groups:
      - adm
      - sudo
    shell: /bin/bash
    lock_passwd: true
    sudo: "ALL=(ALL) NOPASSWD:ALL"

package_update: true
package_upgrade: false

packages:
  - ca-certificates
  - curl
  - python3
  - qemu-guest-agent

write_files:
  - path: /etc/ssh/vault-user-ca.pub
    owner: root:root
    permissions: "0644"
    content: |
      ${ssh_ca_public_key}

  - path: /etc/ssh/sshd_config.d/90-vault-user-ca.conf
    owner: root:root
    permissions: "0644"
    content: |
      TrustedUserCAKeys /etc/ssh/vault-user-ca.pub
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      PermitRootLogin no

runcmd:
  - [ systemctl, enable, --now, qemu-guest-agent ]
  - [ /usr/sbin/sshd, -t ]
  - [ systemctl, restart, ssh ]
