apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-data
  labels:
    app.kubernetes.io/name: nodered
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
