apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-email-credentials-vault
  namespace: monitoring
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/monitoring/alertmanager-email
  vaultAuthRef: monitoring-vault-auth
  refreshAfter: 1m
  destination:
    create: true
    name: alertmanager-email-credentials-vault
    transformation:
      excludeRaw: true
