apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - vault-static-secret-cnpg-minio-production.yaml
  - vault-static-secret-cnpg-wallabag.yaml
  - vault-static-secret-oci-postgres-dr.yaml
  - vault-static-secret-pgadmin.yaml
  - vault-static-secret-wallabag.yaml
  - vault-serviceaccount.yaml
  - vault-auth.yaml
