apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-minio-production-credentials-vault
  namespace: production
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/production/cnpg-minio-production-credentials
  vaultAuthRef: production-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    name: cnpg-minio-production-credentials-vault
    transformation:
      excludeRaw: true

  rolloutRestartTargets:
    - kind: StatefulSet
      name: minio
