apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oci-postgres-dr-credentials-vault
  namespace: production
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/production/oci-postgres-dr-credentials
  vaultAuthRef: production-vault-auth
  refreshAfter: 1m
  destination:
    create: true
    name: oci-postgres-dr-credentials-vault
    transformation:
      excludeRaw: true
