apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-wallabag-credentials-vault
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/production/wallabag
  vaultAuthRef: production-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: cnpg-wallabag-credentials-vault
    type: kubernetes.io/basic-auth
    labels:
      cnpg.io/reload: "true"
    transformation:
      excludeRaw: true
      templates:
        username:
          text: '{{ get .Secrets "DATABASE_USER" }}'
        password:
          text: '{{ get .Secrets "DATABASE_PASSWORD" }}'
