apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: minio-postgres-backups
spec:
  configuration:
    destinationPath: s3://postgres-backups/
    endpointURL: http://minio.staging.svc.cluster.local:9000
    s3Credentials:
      accessKeyId:
        name: cnpg-minio-staging-credentials
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-minio-staging-credentials
        key: SECRET_ACCESS_KEY
    wal:
      compression: gzip
      maxParallel: 8
    data:
      compression: gzip
  retentionPolicy: "30d"

#apiVersion: barmancloud.cnpg.io/v1
#kind: ObjectStore
#metadata:
#  name: minio-postgres-backups
#  namespace: staging-apps
#spec:
#  configuration:
#    destinationPath: s3://postgres-backups/
#    endpointURL: http://minio.production.svc.cluster.local:9000
#    s3Credentials:
#      accessKeyId:
#        name: minio-prod-credentials
#        key: ACCESS_KEY_ID
#      secretAccessKey:
#        name: minio-prod-credentials
#        key: SECRET_ACCESS_KEY
#    wal:
#      compression: gzip
#      maxParallel: 8
#    data:
#      compression: gzip
#  retentionPolicy: "30d"
