apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: central-postgres
  #namespace: staging
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17-standard-trixie

  storage:
    size: 15Gi
    storageClass: local-path

  affinity:
    enablePodAntiAffinity: false
    nodeSelector:
      kubernetes.io/hostname: worker-1

  bootstrap:
    recovery:
      database: wallabag
      owner: wallabag_user
      source: central-postgres-production

  # Register the plugin globally
  # plugins:
  #  - name: barman-cloud.cloudnative-pg.io

  # Configure the external cluster using the plugin architecture
  externalClusters:
    - name: central-postgres-production
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: production-postgres-backups
          serverName: central-postgres-ha
        # ------------------------------------------------------------------------------------------------------------ #          

        # apiVersion: postgresql.cnpg.io/v1
        # kind: Cluster
        # metadata:
        #   name: central-postgres-restore
        #   namespace: staging
        # spec:
        #   instances: 1
        #   imageName: ghcr.io/cloudnative-pg/postgresql:17-standard-trixie

        #   storage:
        #     size: 15Gi
        #     storageClass: local-path

        #   affinity:
        #     enablePodAntiAffinity: false
        #     nodeSelector:
        #       kubernetes.io/hostname: worker-1

        #   bootstrap:
        #     recovery:
        #       source: central-postgres-production

        #   # Register the plugin globally for this cluster
        #   plugins:
        #     - name: barman-cloud.cloudnative-pg.io

        #   # Configure the external cluster using the plugin architecture
        #   externalClusters:
        #     - name: central-postgres-production
        #       plugin:
        #         name: barman-cloud.cloudnative-pg.io
        #         parameters:
        #           # This references the ObjectStore CR we just created in Step 1
        #           barmanObjectName: production-postgres-backups
        #           # This must match the cluster name inside your production backup folders
        #           serverName: central-postgres
        # ------------------------------------------------------------------------------------------------------------ #          
        # apiVersion: postgresql.cnpg.io/v1
        # kind: Cluster
        # metadata:
        #   name: central-postgres-restore
        #   #namespace: production
        # spec:
        #   instances: 1
        #   imageName: ghcr.io/cloudnative-pg/postgresql:17-standard-trixie

        #   storage:
        #     size: 15Gi
        #     storageClass: local-path

        #   affinity:
        #     enablePodAntiAffinity: false
        #     nodeSelector:
        #       kubernetes.io/hostname: worker-1

        #   bootstrap:
        #     recovery:
        #       source: central-postgres-production

        #   externalClusters:
        #     - name: central-postgres-production
        #       barmanObjectStore:
        #         destinationPath: s3://postgres-backups/
        #         # Point to Production MinIO where the real data is
        #         endpointURL: http://minio.production.svc.cluster.local:9000
        #         s3Credentials:
        #           accessKeyId:
        #             # Use the renamed read-only fallback secret!
        #             name: cnpg-minio-production-fallback
        #             key: ACCESS_KEY_ID
        #           secretAccessKey:
        #             name: cnpg-minio-production-fallback
        #             key: SECRET_ACCESS_KEY
        #   plugins:
        #     - name: barman-cloud.cloudnative-pg.io
        #       isWALArchiver: true
        #       parameters:
        #         barmanObjectName: minio-postgres-backups
        # --------------------------------------------- #
        # externalClusters:
        #   - name: central-postgres-production
        #     plugin:
        #       name: barman-cloud.cloudnative-pg.io
        #       parameters:
        #         barmanObjectName: minio-postgres-backups
        #         serverName: central-postgres
