---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-staging-credentials
  namespace: staging
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAZBmKKCulHN9DOp6JSQrh+xFnNbCXfHHpzoEVdgSzomuNFIu6yaXE6zTF8kSmefc984OnQBakQSSk6xjx7wP9F7ubjmix6ivFxeiiL7lUD1OxnFJBCePnzy/hIDctIeJ2KTxoUxtTeDU3Mo8h/BP3rYpdCXnGt8C0NrGr/kF3xKh83MMkbjTKR3EUUgH03s3DRJ8xzBh9q6OircWDpcSeITJf7THqzT3lfUktMtO8br7Dl5W26JwnsE2RZHhP6Mpv4ryVbORy1EaEA9Se1d5jkyKLpiI1XY3jeSImVgWCpRF6PpYU8xuz2RAf0ufd5e/6U55IAFhXPse/WyYGl2wXgkC1WWTajWzYDWlb5CbJ0o8hJkAUecNGeEkO2g+0iBJm2iRuem7AjauD5LexBYWkZdfhXCnxqBVItxrhdzFr/D+wkvp6xcbTNJUWS9lsAhv7e/kIzgGmHkQ1QS8win7OX8qrE2XXIbAzJlMMSaCv77XExgMJMxmY9isz8tJDLbrwalcf86wOvpsjwfeDuNpY434LyadiI3EUtdCE7hSOG+hGZcyo7bGU1nlAxbdTnXwBYy9CQaLpBCSTqpc5VdqY0GKdKikpjLyjX3hJnnBa4TeUtikm5pFVk5YvJUButzlU5eVUheOkcM5h+4R6AgvhI0T9ZSTb/QMkpz4BpAtbSffrGVlkb+GRX8PKx0AZ0AqKi65Ipo1nIFWWTfzUSVRXysQ==
    SECRET_ACCESS_KEY: AgAReqYs+3EwBNd3SiKhwFeRbQeuXwJLsKrB7FyP/KdtNNxTQE+Tf3vsVDZ+JC4/5BxYmPxOUoFa8CP7re0SBKbSiut5v5ImEIKkYw9aA/bsN1/gbYaj+i/WmTIlZInC3T4VD1gNAnyl6mMhqHGKejtQIZcv9CfLCt/fZhIZPO8nuDUujvktCwysVsklkFek+nZPIQLvNfcN497AdKnPbDCNIQ9LxiPjiR6FTYH2XMJoHoOFIU7aRvHaViYXWFV61HJnHelceaTvhYpNOmZ61DtdyezKCSM5JAVCeiSMwq36dgRkcDHeaZcj0RDTgaOJEVGp6U9McNYd6iq1li7bxcW5PPRd7eMQzk3rdIyNDLsC28zDMbnZhagIs8KRMrJkn7/FNb0/ohhEmorwqck9tPpVmO9xmGioBYOl0za1pB8DaUuhGGlRRVNLvDNnuBan1nLQ8BRlUv9/TrNLMrVD3MZlbi1emc+f2JlDGZs9qyTTTEyU8VJvcOv6QfUS0aFImsjL9H5hsn+nsNqr66VV2URClALdFyzM4miQXUvYp5ic4N1BzCRUSBs2y7b4re1MIIUR7inmYtatskEBoXQ57pp2pwac1CHvsEpxXtVe3N8g4silSYmJ/zFoMvxLPnr6/8DB8P+5LGnXLo6es4IsT/XvzODWT08Twe1t3l5TVOy063mwgOrKG3AVwRjq7gTUa7Usp/yVrIv7TUaNLpc6c+szEBPYaZxgtllsweqKwdzDdyYZEz+mxm2vGfXQqg==
  template:
    metadata:
      name: cnpg-minio-staging-credentials
      namespace: staging
    type: Opaque
