apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cnpg-minio-staging-credentials-sealed.yaml
  - minio-credentials-sealed.yaml
  - minio-prod-readonly-sealed.yaml
  - pgadmin-credentials-sealed.yaml
  - wallabag-credentials-sealed.yaml
