---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: staging
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCPnyH6FvShfWVjyVIj0P0GbTrELeRevC1s+3TF7e0PI4LIBu7uGH4tErsRIPrMvzsipq6WVXab9Ohp2Lz1UEv2YgBej959gg0QbaHLtoSdYl1W6B4Ccahn+52EM82RzmAk05wqAPDr6Wh+jY+MO4BBPdV+27iFhAKju1Zvpa5vEJPaHhMxLuzIRX22XNessyKDgGsLyFfbI4O/af9r0BZRPsMYiUlFOev1nHRHjEnrQO90LiUsksxGl9HYx/MMt2SADvyg7JQ6tZ3YKzWlfyhK7HQxQBanaSayx6tHIDfDgpDpOaXvn5p9IzKyUUscSS4YMR47h3aYOrqDCz/YRF5IjFmuOndDRmQxmPROf9DDuCARSl1VFAL1XRSq29Jdk7OiE/drmma8YXghcvxb55yIneP1D64NgKh7lp5fRz/GL3XMzTvwn6vO23/9mKDZm7n8sFv1Z8iCRZyeWwkfeXoAJBWZDUnlX7rkbjxRJblQKsTnHLGIGDuSCADlncR4KD+cSvCFiR8wQV49CfxrnB1O830JpORrgjzJeIeB+VP5RzplSyl7SKgP8SZENtEX94i1cnCc0Hkz5W1tRyQKmtYQOw5YSNZOkYwVKt1KGHlkElYRCFLr6GeEqF5RaUHQry/L7PtruTZkxBVVXWRO6yNHvreOmeSg7wK30RpnpZ06K6nqFMr3GSUtQgSTQ53aupDieW0TRqA0dPpir7s/54whzg==
    SECRET_ACCESS_KEY: AgAK1DpVKw9KBT6THIiNZfBUODzjk2hA9A0DEVyyD0Hk54Ne+nXF1aLIRa7jsv/6LU/2mtwzLCkvdYPUrJRF+B9BtXVizhvnJke628OTj/iw31CEjAvtIfcm+kIE3dYsa17ZxFUpsHP23MvwEbW4OYjTQ4jEjJApdRtj9pNqJUf5Slhz4klxrXXuoK7c8GxqYmLAUlMy1WA1NEivRqCnpQYOiq0bZk8uBQONYvUU4OLvpj1X1xuYpl1z5c1v81eRhqLm5zu4ZS43dooOcBsVGETho7afJdbvlt6veqYAChBpY/hG6SFIKUUem5/xNFxFwkMmrWqi9/J4gXbvgeajoNgz+VphlyK/vadH5XCT5SBB3gShPRm6XlIiJNaz6UXSur7jBd7YLROB0+0wzwygSCtg1zjetgheTl2HUaIKZfm/ZBPN3uCa1ZB+Ik8LwWfONUiEyjIaD/vNEYu9aV3sIfT4bNysYCXmCymtJgEYnv8u3Pv5awruIoEMK8ZfqcmeagWPS7xnoa/aMlyqCKsKcrtVxdcnc31l5oB/oj04aiUwp97DbFPU2Z2WSxooTNn+YK8cEswkNY+prly/2I/dj06kfP02G4J6ImQVEzkKNEDXtFKFar7kGfa1dJdASliiFNUNPpq454vR7b1od38sqTM+0R0Didgx9XOCcx4trhtB8qtBEWDzUprAdVwCdB+fN/LNzulqSZBZyowrhNryeVRbU3c7zcWEzB+/CJ+AzVEJYmahmxy9tbc0VHJ0wg==
  template:
    metadata:
      name: minio-credentials
      namespace: stagin
    type: Opaque
