---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-production-fallback
  namespace: staging
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCJI1XAhrh6jhlxNJ4QvBuIBrgJHUbDS9cN1AZ1mAXTeuk4EH9pmYaQdPVQRkUjc0oyqJGZ31Ju0CFFCWqs625ds8LdKYG5uviejIZAfoCchyPYr5izMQrmbmPpssBwi6EGO+UbcuXOcUtzocs/ftJEHBeGIC+s7qlUJv54lnGHDqfZrorPXpoTSsyeSSy9sABK64wvFsvRdAgo4zFQoKTtS2oIWbz2b9CBTfyxVcEfoijUHedzlj3x4tKxajmzTJno1D/4Ohw8xqN1zd/bOBNtjjDjghIQDHJVOZ77Y3Ku/KsRWSKnuiVsPoZ7Se5IJdpWGovOG81BlmSQBCzLB5V+Lpv/ij3N/a9k0LO21LpwK0+qqxT/Nyh9oYQfjqh4kmNQN6U6nxt118ERVrpvb8xyqhMj9RLfVZAj2hu6NMpGHMk9LuEKAlhxlZ+yIAufo4d2P779q8781kiN+YybvKkFCMeteUkCM92sESEvs1ZHaLVZdocFRz+VnUiwka42lwOQyqbgEwS3U0oMxWsWgDXxEqiF3QYed8K10XVXUD7EI4g7LJwJDaJaIY+EaeQj/g3boP5rbab1K4m6HoKGP4RqChPMlnLUjkdrEkq8NkDfXsO7U6dbpDTho7vLmnAX0ISzit+znE12UBRrnoVg1vJ1Op2xlZtYya1BsF0UfKSe2ZxRtaPzaANCUihddxRHhtIHMpM6Yak1xnQ=
    SECRET_ACCESS_KEY: AgAsxmaqAB3k+w4hKbBEkUAgIvRg4oPozQix80kC61GV9WLzlcDEtM7oyaqLx/rS1QOoVhwDdxQ6jRSmPgXtCmms1+PeI2S4iWN7gPIil1wf6yY0z4tDd38FdDDSAhVdZwGOgIHLgVOVZpZxW3KbDT8Qw9xuA9zham0/TJTvYUlVNhg2wFgKTLxhLJ63AsGITlTD+RdEjRCTqcmG6hxMlIVk3rPpcNPZjcaB8Y5vQAiHP2vggHWOlV3h23hScDtK/27JiidBJ7MFqkX5uKwWIPAkhiPioiZ1G7WWwgxJL8wT/lG9bNrvNqRNMx9t7jquYarUp4/fe9gUs8cxqTiMTFMm1YlVc8dUIcjJkQ2WsH+W3eGVJgcCeyWJf4swuxzFq97a/8XCd0vFoWtUpZYjjPF7itFdRt/KsGClyF+LICR6DI76GLmN9xoYjtT76bIxBBqDIAzPLpl7UFFT0fUDIIjZNp9WygeByVVHWwvPpmzRR0C8xthvy5Ry4sdnLSj2V/rtEprxRrFpU6BVoNY8UNbvQgQcqhRmT16+508pPfg1Q3ZOipY6UdxJnRgVITJVIte/0ei5xg97Z+5i6dnk6No+8jwJoSTXkk8oXZ0D4AaanFQ9eo8tp6LdAtZPynzNHCcX2tvXLaYLa6ZmMWCe7cQoOsPl72G5AeOeF7mxWKb/hqg9dJEnOoMre2Bqrvu6cB4d6ddn2d3lzslv3g==
  template:
    metadata:
      name: cnpg-minio-production-fallback
      namespace: staging
    type: Opaque
