---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-production-fallback
  namespace: staging
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAX5pWM7wa0jf121ytjcRnHKkUDxIJUs0RwUH+NwcEhu4m+IcZ3bvIx/adsguPaRc/3PY5yhh3IO4XrUMqslKbduh24VDtZ6VSR7loO744XkpaMjnFW+ZBx8RuSX+Lga+fuaqOPlE/5K0BXnSqptuSaildttprzkkwcMbfug/TZnZ13kZOiWf98UEQ6Ffu15iEaKSEFPdK2kptrgUbl/n7KT1O7U/VZje8Sov6ziqDS5ehmJVm3Lmt5CPuQ3u5M1IOv7FuIXSw8+0yxj/LUmnVx/7nGF9bBfy5aO/Bl1frh3Nu7CRFswQ/NkuK2iWen46ueemDtf8npM1npezqR5ACv/zVnVm1+MIZUr8HBj1GAjfEo4mCUVNOB90r/yltgPnQdOcxsimn8dPqSEwZaS+14rJ9XXzVZ6FqUYs88be5Qw+wYY7zSh3lzCQzlIXQZEA70ChiRcV/tOFLFXKcFkKZcjAQ9x+wHfdmXC7EHXrn4Panh1/rjzkkEfKcKb+HNc2yIxZ7DJyNofeueEpG68f8x4dFlPxJWltaxk3PALdX7JI8iTPVXhLVbgajZnFJez8WzZYVltKLouLUqnMsfAqaoqiMsdNBMIGUrXhR+d326DWwqQeqqdFb9tcngqXtFyY9tpWqqWCHCRz3ZHULdkv8Ffevdvnjs4vIU+Vk0B3yJs2qTz6Vz9Sm15xWjSby/dYCLZzisHuPsb58=
    SECRET_ACCESS_KEY: AgA2rNqG0iKUCkUIjZH3f7m3HrlHHqTvKrZGvX6fNWgIcyFoqhu2RPgho65yJqpmuYRDP3jYHgJmlUA9KWo0il0PmYeSKAYGeRZGiIURFD/f4r5i2w4lumYW/cIK9POX/oGEPQSRRHBWUZ0CmJUTkaYrNXS1kYCUFoh7c9yi8kiiEinfwi7SPBN2T8aNrTadgSXcxlU8sWrHo6scAh5vndPllzoix+uxPVH/Hm/MKto/JWaxS6Z48lsylqPd8d6ebELo0rGVsBFMOZyiqacXRgv1OsTdetYvpubA6IiJ2QIMoKlMdNlUZmN3XRr/wKC2kKet/0O/N+km1fribr10khjw45SqgkrulWIIYxnukYsL3e/pcBdlW1ehFAvDtsGDVMaO90p6EaesJeJSJ72neNjw6qxMg7vqwux/HFDRsJAebgfPH7ncXb9V4Eru4qbo3oAaE0yuwaCRgiwf4xSP1k/h76Xeoeu/iSp3B+L9Bzyw4RmKBudw761FTeC/9obDaQPNVWva2sdLkV7aVO/YEduLhmlbxgmKAyy1S9zvqHlIqL7eNbmujCREywYoriC3/rI9kTzkc57ewvWoYCbTCoFPhtBzlPgswoSuMx5EnApueSKGhylatcTm/RZhdmSRhJ1Jbx0U88cZtVUhVScWIC+/yLWul2H4DMIVppoV3u25MDeorZ5gYovPkU2MAiCIJwQMgzq4IIrCabaRAg==
  template:
    metadata:
      name: cnpg-minio-production-fallback
      namespace: staging
