---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-credentials
  namespace: staging
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgCDHM80DJmJrxU61LzKX9aqhfqcLvEiOmKqr65Nbgh3nUERuBE6UWr5pzYMMwrlLwXMsKmzcO1z45kaRB+vSobvVIsUjYISudFhVH9Fpu3AGEgvXtghlTfzLjl8+BAguIi3B+L08H9EwzpZjA6ywUAHabEeW3J2MB0IU4o3GIR6mp7k4hyRDZeA9RcLQWQHUdZJx9uh36yRgjWb2DQWrnB/Arvr6I2osMgIPqetZ/WrkjEfKF8P5CB5VVHsoaDpc62chMWm4z34+N85/oyc+7muEVgkM1UxVe4eqdWWg75D/G5j2WclOMTW4Md9kFNgYgxcJqUG1B+kTpgU7aADWQAgfI+N5n+bYOkgiFu81HMDdlC8seBXHdEPtl9rm2ueVE1h0mtD2yXQqAkUq90kpxMbYlUOMADNaazTNxSBxRhATwxlAWxkXQx+Jywtwuu6GEKJn5nhNcuXrSDE+b5hGH034P02qF0NRtrjhHtiMdQftyBLow7PuuB69KhxPXVgbyWV2FzIPAEG5H4gu9wDAbxMtFcPo6Xel/ag5d7hU9n+1UFWa5gQbQkLBYSgTcQAVBFnCC/NU44OqSnFWasPnCqTbHqLpxECpx9afO04hTGgTyuUjnyYZWMIhBq3hmglsaGUuCTGh0iUjg0QxecSqdwBH55KtQMo/8oTVVFbNa7MG2AE8Ck7Eluo8mnABHu8gabycjBWXNzLZr7dudkWmjqBojUPChfehiSR
    PGADMIN_DEFAULT_PASSWORD: AgBdDjRy81jHsY2Ib4JV9zbS92uFmSYfyE4Dd3bXY+gX2R4H6gbF/dSCAxjz/6nsYCg4mFOcm9UjyBcCUOPt+uNk2pHd17OtMr94ZiyCR5c/G5Jv1UafgLu2fsBSVcb7HYxZD7usesPTBID1PlrI7bQ8GaJwzNlrSwfZgGP5tC7GlYYPe/RbF9TGZ1stjBpqsBjOUOrAlV8FSN0zQBeDntgRlZyzwPhY8tvlF87qTMX/TJBGQuV4ZBDBGi1bzfYQ5683EjQMzdg2XlV2+DuGLI8KpS8MWMsmL/iMvIsL9icfDdxeKu4Ee0FVBHcJL9TZuEihNhFEp0Na5DYk/bA7Gm/HBpCuTrjznB34B3bFyWAABl2noAP9be7Y6XfGahrRSUoXLqtt0LLOEb0M3rXDu6Dtpkb7UwuWgusSmWjc0UlgafHNdu4qDull2LeKVRhH9IWTJFLR0EVMj6/2EZSjL9WWzMxDwee5HC/MMRN4YsLRVdmTwMEqgTRh28sRJABL0PY6l5UaFhoW+cBviD7/BrcDEJGHRUkOcf8fIVMKkLRtGepnsFDhpkGOcXlZwo4V4fax9vaVnHgxFbHDqrsKp293QzsdtInaArZkyRPvr5dtrm4PL/OVqsNu1GdUt5Q2ly+x9yUlcxOqqUuMVnXuD42uoMWz1VRzNCt9rvMMJ5Z3AfLGADZ9GgvDjh/B0PtI3dMMp55IeonyJ521Kk/0/VDoyuJiAL6hR8tlsrRNoPJwRbsAtla/sVJQslNDNg==
  template:
    metadata:
      name: pgadmin-credentials
      namespace: staging
    type: Opaque
