apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-smoke-test
  namespace: staging
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/staging/vso-smoke-test
  vaultAuthRef: staging-vault-auth
  refreshAfter: 30s

  destination:
    create: true
    name: vault-smoke-test
