apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-minio-production-fallback-vault
  namespace: staging
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/staging/cnpg-minio-production-fallback
  vaultAuthRef: staging-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    name: cnpg-minio-production-fallback-vault
    transformation:
      excludeRaw: true
