apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: staging-vault-auth
  namespace: staging
spec:
  vaultConnectionRef: vault-secrets-operator-system/default
  method: kubernetes
  mount: kubernetes

  kubernetes:
    role: kubernetes-staging
    serviceAccount: vault-secrets
    audiences:
      - vault
    tokenExpirationSeconds: 600
