apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pgadmin-credentials-vault
  namespace: staging
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/staging/pgadmin
  vaultAuthRef: staging-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    name: pgadmin-credentials-vault
    transformation:
      excludeRaw: true
