apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wallabag-credentials-vault
  namespace: staging
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/staging/wallabag
  vaultAuthRef: staging-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    name: wallabag-credentials-vault
    transformation:
      excludeRaw: true

  rolloutRestartTargets:
    - kind: Deployment
      name: wallabag
