apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-minio-staging-credentials-vault
  namespace: staging
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/staging/cnpg-minio-staging-credentials
  vaultAuthRef: staging-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    name: cnpg-minio-staging-credentials-vault
    transformation:
      excludeRaw: true

  rolloutRestartTargets:
    - kind: StatefulSet
      name: minio
