---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wallabag-credentials
  namespace: staging
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBEJ2srL/vPBZsozIdrQDGy1BWqfp0t5eo3r6UjiHbHurS+gcpcvEwt0baCzmVAWJt0Q5w0zvkH5TQK3sE3uEWnQ9eS2ebErFaohN3N4MhJ9PpyhDoqDAQOUZ8/GDbRvBTxbgj/jkY1O9vRJf5ov/K2i8x/8OF2d16E6UKph9bz1u7M6qxP1fDN41FJmZ2rBXjkhM1txmNKfFKOyH5p+lpV8yd8Y+bY5i/0cohHk12xQgPXY03C+a4OLo7QiI2lKQKaD9RSISBCcSHjO7+xFrWAptDOMXqQoBjWmoq6s290CT4Tq2WUUCp9c6I+Rq8+D/o3ygWJBAWgq5l9uK1Ff1+4VCkRtCGz7G1C7nkU5mKkEzWkGDc67XXYEEWDLJMQ9KFF9nckAjiLTpRclZLEB25r0itHMuIL5VoBCWU37qM8w+H0XSa5CnUeU3JM0lxdH78ojuMAt89XzLJ0Tm1vIdASDVCqxcLLl63yz8Ps51K194Z59I6mrHNU7aDeMjU17+C7aLJXyQusWssOEXmjxuzw1BhBpcV6SI6809cu+GDaa2aVVAn62yVJVf5QRvOvUHvnwTWU0DE9LAN7Gu4JtXEjDkBv/QK/0kDHCx1kwLRankjstv0GoWWk3/eZidAOSNIidstlFiRuRjUenYVQGQHJEAQ59Fta5NE1+62D3KIauJy422iNe7gwNPJdJXWz1z1XXFKxCQ6/VhKA8aHPKZKbSs96/cq8V+XVKCEbHDGj4mXL5nPpjOoUtVqpjg==
    DATABASE_USER: AgB+5joQRliaQtOSQYRkfOIN4MuV2cOcEyly14pyT+mprcctn6JbtfCaquodHj9ry3SePbArCm5rV9X/tGRHX+vAWHrWIMenwlsgiRpGhZ11zIxC3C1cGP6xgyhs0DJCyBT3ySC+Ol3TehtDGeVUFgnV13H7NQtVeewi7CKFy901+XZDoatUg99Zipyu1tLHX2VuLQkKFKcllw5YP3X7cLhqDEQgsbR0EMQ+fuoglE40ci75O2cYyMbrtOzwOalOuZwq6ZGD/9TW5fQafYmjoM4gHxp2DsjulBNlzBWp3b7b0tGkevZlCV8F6kMGl12Rub6ci2m//JgVL8yYLPhfjhc1SZH4XB0krxw0Q7sYs1/U3xxEHY+4DDNBHPQKJ3cMzZ9QBeuCS0V4vuLxA8vtUUZWQPoHgPf7Hs1uO7e+U1kYJ1XxG8D8l9KafgF3b+mNJFPJuR5WErWodqKpZG0z1L2Ss7ZYZKlXphGJ4czOvo+sHLIsctbZ7PXqpzjQHD5HlkAr90Bm8CA2il0zl3ctXVDJsVUlUyVIMiSqzpSI9ceIQ23ZQjmyDEkdKqc9FKPDpmrWuQMfNCPQ71KHeLHU+g2X1LcRsjtONMhiyey/+eoxFqdpZVdlFJlPuvkFHDmTVu28XnVmP1X2w2mV9MgeJd2HaP4kPLYw2XylcbzrJYul3JHEGkP7OCI3bjyJcaUA6lYmnJxfpsRqE45Fh9hIvcj/xawdHt0=
  template:
    metadata:
      name: wallabag-credentials
      namespace: staging
    type: Opaque
