apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-postgres-bucket
spec:
  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: mc
          image: minio/mc:RELEASE.2025-04-16T18-13-26Z
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb --ignore-existing local/postgres-backups
              mc ls local

          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: cnpg-minio-production-credentials
                  key: ACCESS_KEY_ID

            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-minio-production-credentials
                  key: SECRET_ACCESS_KEY
