apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: first-backup
# namespace: production
spec:
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: central-postgres
