apiVersion: apps/v1
kind: Deployment
metadata:
  name: docmost
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-1
      containers:
        - name: docmost
          env:
            - name: APP_URL
              value: "http://docmost-dev.home"
            - name: REDIS_URL
              value: "redis://redis.dev.svc.cluster.local:6379"
