apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../../base/minio
  - ../../../base/redis
  - patches/minio/minio-local-pv.yaml
  - patches/minio/minio-bucket-job.yaml
  - patches/cloudnative-pg/barman-objectstore.yaml
  - patches/cloudnative-pg/central-postgres-dev.yaml
  - patches/cloudnative-pg/health-database-dev.yaml
  - patches/cloudnative-pg/scheduled-backup-dev.yaml

patches:
  - path: patches/minio/minio-dev-patch.yaml
  - path: patches/minio/minio-pvc-patch.yaml
  - path: patches/redis/redis-resources.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: redis
    patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - worker-1
