apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  template:
    spec:
      containers:
        - name: wallabag
          envFrom:
            - secretRef:
                name: wallabag-credentials-vault
