apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Automatically provisions a dynamic sandbox directory
  resources:
    requests:
      storage: 5Gi # Scaled down to save homelab drive space
