apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - vault-static-secret-cnpg-minio-dev.yaml
  - vault-static-secret-pgadmin.yaml
  - vault-static-secret-wallabag.yaml
  - vault-static-secret-cnpg-wallabag.yaml
  - vault-static-secret-cnpg-health-ingester.yaml
  - vault-static-secret-cnpg-health-grafana.yaml
  - vault-static-secret-health-ingester.yaml
  - vault-static-secret-n8n.yaml
  - vault-static-secret-cnpg-n8n.yaml
  - vault-static-secret-authentik.yaml
  - vault-static-secret-cnpg-authentik.yaml
  - vault-serviceaccount.yaml
  - vault-auth.yaml
