apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nodered-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/nodered
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m
  destination:
    create: true
    name: nodered-credentials-vault
  rolloutRestartTargets:
    - kind: Deployment
      name: nodered
