apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-docmost-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/docmost-cnpg
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m
  destination:
    create: true
    name: cnpg-docmost-dev-credentials-vault
