apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-health-grafana-dev-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/health
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: cnpg-health-grafana-dev-credentials-vault
    type: kubernetes.io/basic-auth
    labels:
      cnpg.io/reload: "true"
    transformation:
      excludeRaw: true
      templates:
        username:
          text: '{{ get .Secrets "HEALTH_GRAFANA_DB_USER" }}'
        password:
          text: '{{ get .Secrets "HEALTH_GRAFANA_DB_PASSWORD" }}'
