apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pgadmin-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/pgadmin
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m

  destination:
    create: true
    overwrite: true
    name: pgadmin-credentials-vault
    transformation:
      excludeRaw: true

  rolloutRestartTargets:
    - kind: Deployment
      name: pgadmin
