apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cnpg-authentik-dev-credentials-vault
  namespace: dev
spec:
  type: kv-v2
  mount: kv
  path: kubernetes/dev/authentik
  vaultAuthRef: dev-vault-auth
  refreshAfter: 1m
  destination:
    create: true
    name: cnpg-authentik-dev-credentials-vault
    type: kubernetes.io/basic-auth
    labels:
      cnpg.io/reload: "true"
    transformation:
      excludeRaw: true
      templates:
        username:
          text: '{{ get .Secrets "DATABASE_USER" }}'
        password:
          text: '{{ get .Secrets "DATABASE_PASSWORD" }}'
