---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-minio-production-credentials
  namespace: production
spec:
  encryptedData:
    ACCESS_KEY_ID: AgB5yI6SRVrW296g3xCDETpbLXqmWra1DewF61o1DsY6oUxPiObAkk1HhedTEsI6S0Uh5chMleHwXlYqrIbcVBRsPHvk97eM09CLa5u3osRTPlPcbA3XYAEgEiCjHxzerCvjCHH9IKEX0nRsG4sB0/r5EC1rVkID3bKN4ZsjB2iOG1YUoJQd2oDzEOycwd6wpXbknq816VUHsq8uMOPsX95WAZqsedxr2fKo36EpbrL6pK4wW5lKSU+KXllEJc7B1lQ0DvMdNrGjzJeKcTM8DcO8cxhoSRDjvyLqaK+mB0VU1lV3dQzJj4q5iqoyqzk8Eke3gJBTpaZgsGy7i0HSwDqg05I3nzeo8SBMxVDNUG+i0U2ZK/gexmaAgUKGLLOUd9sUZZUe5mmcpXw0/FLR9MzDs9lhM1h7hPbqaWBVIlqXkl2OvGY2ugY1mntrY8oSRBmcsytUYIXiowUVAxjW3O5F4+db4NhlO6jbjSP8OpFnpOK3qWiimD9Txhh3B9ir/C4dJHpoBFI/OEcQDhnU6cJd0vcmHwDU5dQGk5Tdtbfx1csLYqLiqCF+GwUmxKeIdLqVnox0xfPiaeZXxv7n+O2+1ey3fMRb9g8XKfaI1MJZCgNP8ZQ4VcZpCmj/G4B1yShkQ4v2SE1B6Yee/Or4/jmfRNjhhGGFFxQSIEYz/3iELFQ68SGZaaeBCygYtb3GudaxfcG/ps0cfRYqbBkLj1BgFavL6A==
    SECRET_ACCESS_KEY: AgCRfbsmYnUL0LE6MqJEbKVKYg3aI/zgqQ79J1VBuEh1QTQG9DLgs6P3DiXVeRs3C5kZJe+hNN1Cf7unRzLoLNAnqryglD/TMUbUYuFNpXQVN8C0scyyEMGEIuoR0KssFPh5QydsRsyjSExmGWoNcTi8OUylJCNTbgUyIAxYX+9UdxqL0Oi6eCdNhcu9SqLCaMgu9GcyeM39iCbQxwzW0cbd7xSkSM8v8RUrPBfCwSsMPLrW5U/xiZLxpoa4gpyfMWZ4aktSIAlh6sZKynTSunI/0HVEdEUSHdL2zFRzx/tbljxMtEfaN64nGwaZG3VuGWitv+kT45QAnibkuzmWqGE/8muHJo9WAoom00ZQNY2njsaJcMH/mDixtEHIw00lLtQ8Nn6/w9H5N7lQjEhLxFCRJrGf1sUqeFBGbt6yIJ8/BPxMMX60h+7S5i6oZq7Et1G2ZQnVfCSrlXTW/mTpwMKnFAElk56vmNJ4Tk6ifH5gEFzw1rb0XBIaar5psjNMzfkgRrOZIxEjrnlXR03MNrXWxlIZ9VrWLC3FKaLvGoN2oS96h7hcX6CILPRL/fNGyQawp3jKAiR+FftWccZ5Nz+gxe2UX6EXhBPpp7j6/Tsqv8OTuJZW/95pJzXRRTMXhxlJ/6H9HnQbJ+MC0qXsWdc/NVoPfdAdzKwj/Ji3yL220LO8bP9DlkUcc+oHz9lNFi+lBy749gCZbwgk9NglHSNe1s+9IFJRzU0JWTaBG4dc72S/WE4uXvI4/o1t
  template:
    metadata:
      name: cnpg-minio-production-credentials
      namespace: production
    type: Opaque
