---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: production
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBGhDF1bKP2ykuwvoUnIus4f0AkpByV2HoIGUWMUoJ+kZ7zZwv2Zbu1TLuajE4rt3RbQcPJlwuKHE8lhjFqmdpS3YjTikAXk/68LArtgT+mFNpV5YI1SoGr0gqfCMYXfdDKKb6PDdWY65IJ6ITH+vr0Pg3tFGHymq9QTRtlM+XZWzZBsllDyJeBZkTfUOHKVVyqann8tZL6/j3aunkceCpIYaq0rlkF36M3jY/RO+h1QSEd0fP37Rc9XDdiACIvm+Zq7b/F8UYVqC5xRNuFT91vgOWltSnVnPNq13dHPuDbZLZ4l9Z98veKcIAlc4d8mw8LplsrDk2q5azRBTrpR882h2BjxtDg61rq10R1bfYoBA7Rrw6sdLqhYidndC1COPMTvSNa+be5Hp28LT+UG8M7/0UtLCxuK7uKlZmiT7sv9po2ZL5TuIJ5K7lqj7PY89tZExB5HYBAoVGQ3sDVGO1k0oI3hJrypcsD0bpgZedsyquXTvZBnry+V1Qorg4vS8u5MgqAsZ+ZaxqyBFkXXikbTOWsV+dm7qGGY7LYC2GQdn6zPsCpooUgj6b5Kpf5Z5WwSs/p9AlbtQ8XJ7HyDwz9aKxhQpHwU1rAwsNQOsN9GS7/gs8701s5shAiZlYFMxJ+Nl7y37CdvJyREfxuPidx9xo7kSU3CP2heYBlPNDhNlAJeiFU7QpVH76IAROkpgq9WkacDdbAAIY=
    SECRET_ACCESS_KEY: AgBmZsPqlQq8Jl5ty8EJ0UdSUWyJXpUKXAo4qyD2ICf0tP/QSAkiSI9frUkCWb+1T05JQiyVKhchfnvj4azHjJkij5KyBaQqhGIPFEGzyUSOLXWYARKBXIAlDDxG+2Q3YIDwkencEMqdUV1EZxlfJXb6Q1MTDG/ktNP/lca+z3q7V6aSC6rub+vRpvWjOsY3onOwoXo3oTbzZ1ExAEHy917Vw++4rZU/Wu4/FjR8/qBKCmCjsvsIqwGT7hp7SfM1i24SVI290ab8pvMWwJ/iasEZJhoGowgUOvYeu2m8w61h1DWFrcKu3UEuCSftwpMl1h/W8eRcd109FLjb2EvvCpuarXhxQnqSCqwZk7x1SqJXhCspSV9o3FjEWM1B3Z0kbdR5CPBEYdw7kFTdVK/fRHjopfnWyhMANMe0P1CnNUxUyHlH1NSHxV8NiP6F/ClGUp+zDd9SnwonejTsXumXOC3rlLuh6erTgAO8ezekJjfMk04ILU/GhuAqPVLfP37Hd0hkSS5kN4m6zbIqfNeZVK7ZYjKexWacxLLgdcpvpyDIyx17sGK0DO/urMYPCDUKgV9BOIccRotER/HPxOCywhJlBpO8Vb79POENw7omd5jbUMU1BAD7oLakFOKpayN2xUdQ/4WUVyOb01NYMNl8T1HTeg1l6hSsQ+j15FxBkPW+JC/ts4J9N1U7FwN1qAZPCM9toNU/I+zRYQ9VXQ==
  template:
    metadata:
      name: minio-credentials
      namespace: production
    type: Opaque
