---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-credentials
  namespace: production
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgAy+Zp4H92XYiBiXuCWepicRauiDOHQlifnNBxVf8ZSkgneYZKHwrLyUR1ToSS7N8QxHQD8lqustFaHhruUPgpoeo3xj3hozSB9hSD4+9vOpECRNeDXtmRx21v8G07sv4NS5EJzbMbbDGspaOFdQEObiQAcPHImmOJf/yfPKc2Cy1Lt6m/Rnpe9qsozgmbO+4S7cNGpYtnTrNbsBbemHC7a0nWLz+gXTXnLesTvE7fUp2Kxy8l1Hz51NXhn3i8gtU+yCHm0Qva7XDff/iLaOp+tiS9OXSZD47XvQkQkmsE8OHopupnl6lX9jgPjkSKTko1889o7lNNjT+yLdqVk+tXaeVWC1y7b5EWd2tj/IVfjRQpdxakBfAlaq+lRxbiDL8MH84hP8wkqMUlhLQY0N5sN4NBSAvgcmT88MiByCaYqT5W9cq5OxC4Z/mfuK+jYV0NgZ2PogD1hpIkk7rDLcBwsNmpRWGKJr3Lpp2VYdtiT6qkSDTuVp6silxp0tSpu+O2bRcNh+BksS1ejU7Ibf/CFO4qY5/85OwTmUOU+kUMBiVO5Hih9tSxKRcuXpVzVGtdzL5q4p2EL4GB3MZmqeVFX3bCaf99y9iRo18v5a3ZqNG+bFUmvqOFrbf5jRYnmo4WHBa4iwnh92oX/IuwTxqI1d8cEaYKn1NBjcHBWGV81QTX/i3Sgcih99167CKxLvApfviiy2W04kvOb55/8L7TOWw==
    PGADMIN_DEFAULT_PASSWORD: AgCzsiKHprPs0OImOVd3VNaZj0oGrf8OngEp/b6dQcLLytILEQ8mZb4zDNEGRh19nR9DdMtnEGlfW9Sm+e0qZ33xdBG8V0jnC63cQQ26U116bWyTqv36/qJjWueU6ZESBILkCV4JKaZnKxY9KqX8igdNA0Paq0XgM3NJRlE/x2ySTMmDgu8mLJNnCsRktt7feYq8YXZB+lgtCSAKfrwtrMfznSGgqnC4AgETA1IEJQzORCmeCvR8JJB9esbGt8UAb6JLL8A9TQxIpYFXiL5qdK6rq91Tv64EggXBwrDLaXqekFdVIPocU5S6WbGun0+2fyRSitFqzPZun9PuHVrSlNvXxkHop/3sBLC/f7dQK7i7Awgvs8ybauapdrr+7deKoVUZiijTMt3nr8WRrhPNIi5zKnv0MvtH5Nzuh0Kbyb6AOzT3XBECFgwwgH0FdMPdrMRSV4wFTOXah0Rz99mVMvHs++d/PxD45bqsoG64jkRHbiGt0M73sVO6b7YNyOFf2+9GL/wRTFd1uPMd7vLFuCibNtVrt5Ke0HYlBPGdk4M7knx5mWLRsMV2fEwA9k3KyEp6OKcXyGEh7+5z1ml5NCLXtJq487iuh/in/tWjUmt5RUaumau49wyt8mKy2T4i/7mQHIygptMh5KR7IjT27Dk9jJe30WBdVjWx7rYfGeDvBC8UYalYzgqytIuiq/b1IS9EUuM8xRk6jkrMyQ==
  template:
    metadata:
      name: pgadmin-credentials
      namespace: production
    type: Opaque
