---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wallabag-credentials
  namespace: production
spec:
  encryptedData:
    DATABASE_PASSWORD: AgB1ofEjepDMHHh/8/r9zpVle1H0Pyjz4K2vvDYvAElEruZKf7lrbVe/W4ZGOaqIiP+WwhOPkKxP0+ul33tDa5cAQwsbS3HttS0pg4z19E7KcliAIEqzOxeKwvTxIrha0skImiTSFwHCrPQUP8Bm0YCJEKiR7RQKL52hCuS+sxmbbNKRe8bk+FPnHf7cLTbVaovshrrfdEwRHB2We0vLh5wse0VQdL9FfSGZ5SWw3Jz8pcXpNOVds8R5rpiispBQdAzze7EnXUQ9hU1uxFGA4ABPg1pNexp/ROuY83N83WAXsovL7yl5uWIXixTm13wMIXLOmobXXHvAPaNzQEJ4yjD3dgkSTLFhTv0vjew/Z39MVyJsXSmWuARzeswXAT94ON7XuZgT/7Ch8gR8YP7D958lKs1N4ADFMQaum+tG0QogS2jDDiBt342Z9y7f9umJZ9df4GoN+NEFHoUvd5Ip1b2T3RNT/pIJlTHLROwrgojB2S5ZakuGrMSurLkTZzWAynUN1i9/bdV37tpn1Z7+hrw3AiWy2MT2g7i07a9EOyFuF3QeblXmW48pY/bFXF3qaBmxq/MKp97LYdZZ2vQ6Qnc/LeEJ6Tqhe6n3lW5tp7rN6W+jL4kz3Yd3jUGWC+cvtFkVzXKkNIkAWQkOM4VSSWcs7atCNXeecfxnahkqX3cbsKmJkFIW1sY95NuJHGl2WBZd8Rg+3Rjiqi/z78/ORzM8la4SJdWuQp4UDWxPIjOpoAKnxXEvKdwEa1Fhqw==
    DATABASE_USER: AgANy1LBmUuliJ46wqeZ24kYRNs2tn5TQtRIkiAPsq4qa+B4SB7TVj7Y4B1K36faXN4V7Q/pO/lIPJTnUM5siO9kCGwP03aALeW1I4tB31CaTV/Y3B86LC1QHf8jEz56jfTuFwiZaIV4ZAx7RpwzksNnyipegpamj3NywWN7IGkWPl89VlbXl908uIbQ1tWWJY21VwI671diZWCruxZHDH11FrBUa7rcUU2ps+Z1BA9H3lOyC61l48WI7FD6lJ6Hy6L4WOqBzgg05wX1S93pIpAq6z3tqxne4hy4mcUe1DXXBkA4pB4GQetKMxJArg1WpjdTjpf3cNs5nIUfi3OWfRKjDNFoLBwjk7pUAjhBMsHxC9eUi+jAQKUt1q2xAMtfluClkwKAc38zOYf4+AEbmhZ+8pHswiXotOlsze/CLoLWZ/E+EW1tClvoGeQWbOCJd0yadOOIaXIyl7LeWkc4Kx6c2CZ0k4Q1/9xmNPyPCRVqK5q1zLj8C2e9mB9MaEozjFG8Kn2a2nXdf/Myg5oS5gzQOxI9zSsPEzepWzzlwXTRJBY9Wgo62aaOOC7+IMe7kiwYvibxglcefg2GDu4/ofz5KOW3MHw+RC9IyGK5pg/TK1WYf8n2kQiy1eE9wa0IZ95rH70wV/zozAMqj/QxtZGmUsOfTqNTrzgokhilGdlSa7MRyVe5F29E+CLgjpcsSMsbHkXlU35ZxwS1jzR4
  template:
    metadata:
      name: wallabag-credentials
      namespace: production
    type: Opaque
