name: Cleanup VM

on:
  workflow_dispatch: # Allows you to click a "Run workflow" button in GitHub Actions
  delete: # Runs when a branch is deleted
    branches:
      - "**"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # --- ADD THIS STEP ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      # ---------------------

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.LIBVIRT_SSH_KEY }}" > ~/.ssh/id_ed25519_github_actions
          chmod 600 ~/.ssh/id_ed25519_github_actions

      - name: Terraform Destroy
        working-directory: terraform
        run: |
          terraform init
          terraform destroy -auto-approve \
            -var="libvirt_uri=qemu+ssh://zshamsadd@100.92.179.76/system?sshauth=privkey&keyfile=/home/runner/.ssh/id_ed25519_github_actions&known_hosts_verify=ignore"
