apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-1
      containers:
        - name: n8n
          env:
            - name: DB_POSTGRESDB_HOST
              value: "central-postgres-dev-rw.dev.svc.cluster.local"
            - name: DB_POSTGRESDB_DATABASE
              value: "n8n_dev"
            - name: N8N_HOST
              value: "n8n-dev.home"
            - name: N8N_WEBHOOK_URL
              value: "http://n8n-dev.home/"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_LISTEN_ADDRESS
              value: "0.0.0.0"
            - name: N8N_PROTOCOL
              value: "http"
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "false"

          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
