apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - ../../base/minio
  - ../../base/pgadmin
  - ../../base/redis
  - ../../base/wallabag
  - ./secrets
  - ./patches/minio/minio-local-pv.yaml
  - ./patches/cloudnative-pg/central-postgres-ha.yaml
  - ./patches/cloudnative-pg/barman-objectstore.yaml
  - ./patches/cloudnative-pg/scheduled-backup-ha.yaml
  - ./patches/cloudnative-pg/oci-postgres-dr-mirror-cronjob.yaml
  - ./patches/minio/minio-bucket-job.yaml

patches:
  - path: ./patches/minio/minio-vault-secret.yaml
  - path: ./patches/wallabag/wallabag-vault-secret.yaml
  - path: ./patches/pgadmin/pgadmin-vault-secret.yaml
