apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../base/pgadmin
  - ../../base/wallabag
patches:
  - path: ./patches/wallabag/wallabag-vault-secret.yaml
  - path: ./patches/pgadmin/pgadmin-vault-secret.yaml
